### ISSUE TITLE
Error - Running the script (Syntax Error)

### ISSUE THREAD

**Issue by pcmrityunjoy** [kubapilch/Show-Details#1]
With all packages installed, the script runs into below error.

Python Version: Python 2.7.12

>python Show_Graphs.py -l https://www.imdb.com/title/tt0475784/ -a -d rv

```
Traceback (most recent call last):
  File "Show_Graphs.py", line 3, in <module>
    from sources.api_imdb import API_IMDb
  File "C:\Users\Soumya - PC\Downloads\Show-Details-master\Show-Details-master\sources\api_imdb.py", line 20
    print( "\r"+ (" " * (lenght+71)), end='\r')
                                         ^
SyntaxError: invalid syntax
```
Thanks!

**Comment by kubapilch** [comment]
From what I have found the issue is that you can't use `print("foo", end"foo")` in python 2.7. I will try to refactor my code to be compatible with python 2.7. 

Now the only thing you can do is update your python to version 3.x or wait until tomorrow as I will release .exe file of my script.

**Comment by kubapilch** [comment]
Can you please try it againg after my last commit?

**Comment by kubapilch** [comment]
From what I have found the issue is that you can't use `print("foo", end="foo")` in python 2.7. My script is compatible with python 3 and higher so you can't run it with python 2.7.12.

The only thing you can do is update your python to version 3.x or wait until I release .exe file of my script.
